import time
import streamlit as st
from services.message_assistant import draft_reply

st.title("AI-Assisted Airbnb Guest Reply")
st.caption(
    "This tool assists Airbnb hosts by drafting replies. "
    "All messages are reviewed and sent manually by the operator."
)

st.markdown("### 1. Guest message")
guest_message = st.text_area(
    "Paste the guest's message here:",
    placeholder="Hi, what time is check-in?"
)

st.markdown("### 2. Reply settings")
tone = st.selectbox(
    "Select tone",
    ["Professional", "Friendly"]
)

# Initialize session state
if "reply" not in st.session_state:
    st.session_state.reply = ""
if "last_generated" not in st.session_state:
    st.session_state.last_generated = None

st.markdown("### 3. Generate reply")
generate_clicked = st.button("Generate Reply")

if generate_clicked:
    st.session_state.reply = draft_reply(guest_message, tone)
    st.session_state.last_generated = time.strftime("%H:%M:%S")

st.markdown("### 4. Draft reply (editable)")
if st.session_state.last_generated:
    st.caption(f"Generated by AI at {st.session_state.last_generated}")

st.session_state.reply = st.text_area(
    "Edit the reply before sending:",
    value=st.session_state.reply,
    height=180
)

if st.button("Clear draft"):
    st.session_state.reply = ""
    st.session_state.last_generated = None